CREATE DATABASE customer_behavior;
use customer_behavior;

/* 1.what is the total revenue generated by male vs. female customers ? */
select gender , sum(purchase_amount_usd) as revenue
from customer
group by gender;

/* 2.which customers used a discount but still spent more than the avg purchase amount ? */
select customer_id,purchase_amount_usd
from customer 
where discount_applied = 'yes' and purchase_amount_usd >= (select avg
(purchase_amount_usd)
 from customer);
 
/* 3. which are the top 5 products with the hightest avg review rating ? */
select  item_purchased ,round( avg(review_rating),2) as "avg_product_rating"
from customer
group by item_purchased
order by avg(review_rating)desc
limit 5;

/* 4. compare the avg purchase amounts between standard and express shipping. */
select shipping_type,
round(avg(purchase_amount_usd),2) as avg_purchase
from customer
where shipping_type in ('standard','express')
group by shipping_type;

/* 5. do subscribe customers spend more ? compare avg spend and total revenue between subscribers and non subscribers */
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount_usd),2) as avg_spend,
round(sum(purchase_amount_usd),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

/* 6. which 5 products have the highest percentage of purchases with discounts applied ? */
select item_purchased ,round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end )/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

/* 7. segement customers into new, returning , and loyal based on their total number of purchases, and */
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer
)

SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;



/* 8. what are the top 3 most purchased within each category */
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders ,
row_number() over(partition by category order by count(customer_id)desc)as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

/* 9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ? */
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

/*10. what is the revenue contribution of each age group ? */
select age_group,
sum(purchase_amount_usd) as total_revenue
from customer
group by age_group
order by total_revenue desc;


SELECT age_group, SUM(purchase_amount_usd)
FROM customer
GROUP BY age_group
ORDER BY 2 DESC;

/* ALTER TABLE customer
ADD COLUMN age_group VARCHAR(50);
SET SQL_SAFE_UPDATES = 0;
UPDATE customer
SET age_group = 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN 'young adult'
        WHEN age BETWEEN 26 AND 55 THEN 'middle-ages'
        WHEN age > 55 THEN 'senior'
        ELSE 'unknown'
    END;
SELECT age_group,
       SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC; */


















